# Carga de datos capturados con el OZM

## Primeros analisis de cargas de datos ¶
En primer lugar, se analizan metadatos y datos del dataset cuya estructura deberia basarse en el formato NILMTK-DF.

Contemos el numero de filas de cada fichero de datos en el nuevo formato parquet

In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
def modulus(val):
    """
    get modulus of a complex number
    """
    res_val = []
    #print('modulus')
    if (isinstance(val, list)):
        for i in range(len(val)):
            val_item = val[i]
            #print (val_item) 
            if isinstance(val_item, list):
                if(len(val_item) == 2):
                    res = np.sqrt(val_item[0]**2 + val_item[1]**2)
                    val_item = res
            res_val.append(val_item)
            #print(res_val)
    else:
        res_val = val
        #print (res_val)
    return res_val

def array_to_list(array):
    """Convert numpy array to list"""
    if isinstance(array, np.ndarray):
        return array_to_list(array.tolist())
    elif isinstance(array, list):
        return [array_to_list(item) for item in array]
    elif isinstance(array, tuple):
        return tuple(array_to_list(item) for item in array)
    else:
        return array

## leer un fichero de datos

In [3]:
df_path = ".\data\ozm1\ozm_fan_200MS.parquet"
print(os.path.exists(df_path))
print(os.getcwd())
df = pd.read_parquet(df_path)
item = df.iloc[0]['Voltage_Harmonics_Complex']
print(item)
print(type(item))

True
C:\Users\carlo\jupyter_notebooks\ozm_datos_completos _noviembre1_ALEATORIOS -TRANSITORIOS
[array([-47.1264, 235.281 ]) array([ 1.47897, -2.95887])
 array([-1.47061, -2.26567]) array([ 0.794973, -0.608901])
 array([ 0.174636, -2.56696 ]) array([ 0.092656, -0.006175])
 array([-1.44591 , -0.490085]) array([0.077261, 0.141361])
 array([ 0.746942, -1.20341 ]) array([-0.304748, -0.198415])
 array([0.200122, 0.037235]) array([-0.178479, -0.330504])
 array([-0.169268,  0.187881]) array([-0.037933, -0.337815])
 array([-0.133603, -0.04289 ]) array([ 0.120017, -0.274384])
 array([-0.275936,  0.097135]) array([ 0.181769, -0.139061])
 array([ 0.189442, -0.35024 ]) array([0.120751, 0.004086])
 array([ 0.047056, -0.218427]) array([0.000966, 0.016745])
 array([-0.057723, -0.213405]) array([-0.077143, -0.025767])
 array([ 0.122208, -0.100879]) array([-0.079057, -0.108737])
 array([0.074424, 0.002932]) array([-0.028662, -0.163397])
 array([0.008933, 0.016485]) array([ 0.046322, -0.154046])
 array([

0        [239.95425926196853, 3.3079093001169184, 2.701...
1        [242.12684891868145, 1.5281954031615197, 1.084...
2        [242.5702061057994, 0.2218705199209665, 1.8971...
3        [242.50256694082643, 0.14188803530248772, 2.03...
4        [242.53347239059602, 0.01846863841759863, 1.98...
                               ...                        
39403    [244.75933004190054, 0.32007489714908915, 1.89...
39404    [244.6773134517379, 0.05796792183613278, 2.032...
39405    [244.65726304248562, 0.02422492010306742, 2.00...
39406    [244.6480277329249, 0.015282713404366387, 1.99...
39407    [244.4975795552177, 0.2887791588272949, 2.1860...

## Convertir el array en una lista

In [4]:
df = df.applymap(array_to_list)
item = df.iloc[0]['Voltage_Harmonics_Complex']
print(item)
print(type(item))

[[-47.1264, 235.281], [1.47897, -2.95887], [-1.47061, -2.26567], [0.794973, -0.608901], [0.174636, -2.56696], [0.092656, -0.006175], [-1.44591, -0.490085], [0.077261, 0.141361], [0.746942, -1.20341], [-0.304748, -0.198415], [0.200122, 0.037235], [-0.178479, -0.330504], [-0.169268, 0.187881], [-0.037933, -0.337815], [-0.133603, -0.04289], [0.120017, -0.274384], [-0.275936, 0.097135], [0.181769, -0.139061], [0.189442, -0.35024], [0.120751, 0.004086], [0.047056, -0.218427], [0.000966, 0.016745], [-0.057723, -0.213405], [-0.077143, -0.025767], [0.122208, -0.100879], [-0.079057, -0.108737], [0.074424, 0.002932], [-0.028662, -0.163397], [0.008933, 0.016485], [0.046322, -0.154046], [-0.062197, -0.029588], [0.086485, -0.09622], [-0.081693, -0.07707], [0.070404, -0.030858], [-0.013065, -0.118176], [0.029716, -0.003488], [0.035126, -0.156638], [-0.023431, 0.003919], [0.057712, -0.093271], [-0.055876, -0.065713], [0.071439, -0.036159], [-0.025111, -0.10536], [0.038306, -0.014132], [0.014752, -0.1

## Calcular el modulo de todas las partes complejas para el campo voltaje

In [5]:
df = df.applymap(modulus)
item = df.iloc[0]['Voltage_Harmonics_Complex']
print(item)
print(type(item))

[239.95425926196853, 3.3079093001169184, 2.7011024269731054, 1.0013703103897178, 2.5728935800176425, 0.09286153649924171, 1.5267085626683963, 0.16109684802006524, 1.4163749431079329, 0.3636479832599103, 0.2035565280431949, 0.3756163567484782, 0.2528852031752748, 0.33993806305561014, 0.14031861497677348, 0.29948398912963614, 0.29253356101650974, 0.2288622535107089, 0.3981913220601373, 0.12082011172400066, 0.22343818264790824, 0.016772840576360346, 0.22107383100222425, 0.08133253185534065, 0.15846566790633232, 0.1344386269566898, 0.07448173198845473, 0.16589180164492756, 0.018749765705202825, 0.16085987007330324, 0.0688760956573469, 0.12937520483075574, 0.11230997795832746, 0.07686962586093417, 0.1188960100297735, 0.029920006684491234, 0.16052818730677798, 0.023756479579264266, 0.10968206045201741, 0.08625732284855588, 0.0800687454753726, 0.10831108863362052, 0.040829683564779194, 0.1096855515781363, 0.010840543528808876, 0.11210742407173577, 0.05712045890922096, 0.06926390931069369, 0.0

## Ejemplo completo

In [6]:
def modulus(val):
    """
    get modulus of a complex number
    """
    res_val = []
    #print('modulus')
    if (isinstance(val, list)):
        for i in range(len(val)):
            val_item = val[i]
            #print (val_item) 
            if isinstance(val_item, list):
                if(len(val_item) == 2):
                    res = np.sqrt(val_item[0]**2 + val_item[1]**2)
                    val_item = res
            res_val.append(val_item)
            #print(res_val)
    else:
        res_val = val
        #print (res_val)
    return res_val

def array_to_list(array):
    """Convert numpy array to list"""
    if isinstance(array, np.ndarray):
        return array_to_list(array.tolist())
    elif isinstance(array, list):
        return [array_to_list(item) for item in array]
    elif isinstance(array, tuple):
        return tuple(array_to_list(item) for item in array)
    else:
        return array

In [7]:
 
    
    
    
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_fan_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('fan.csv') 




    


## Comprobacion de numero de filas para cada fichero

In [8]:
with open(r'.\data\ozm1\ozm_fan_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero freezer=',len(df.index))

filas fichero freezer= 39408


In [9]:
with open(r'.\data\ozm1\ozm_freezer_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero freezer=',len(df.index))

filas fichero freezer= 39409


In [10]:
with open(r'.\data\ozm1\ozm_fridge_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero fridge=',len(df.index))


filas fichero fridge= 39409


In [11]:
with open(r'.\data\ozm1\ozm_kettle_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero kettle=',len(df.index))


filas fichero kettle= 39428


In [12]:
with open(r'.\data\ozm1\ozm_microvawe_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero microwave=',len(df.index))


filas fichero microwave= 39429


In [13]:
with open(r'.\data\ozm1\ozm_monitor_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero monitor=',len(df.index))


filas fichero monitor= 28945


In [14]:
with open(r'.\data\ozm1\ozm_oil_heater_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero oil_heater=',len(df.index))

filas fichero oil_heater= 32488


In [15]:
with open(r'.\data\ozm1\ozm_oven_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero oven=',len(df.index))

filas fichero oven= 39429


In [16]:
with open(r'.\data\ozm1\ozm_vacuum_cleaner_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero vacuum cleaner=',len(df.index))

filas fichero vacuum cleaner= 39427


In [17]:
with open(r'.\data\ozm1\ozm_water_heater_200MS.parquet', 'rb') as f:
    df = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero water_heater=',len(df.index))


filas fichero water_heater= 39409


In [18]:
with open(r'.\data\ozm1\ozm_aggregation_200MS.parquet', 'rb') as f:
    df_datos_agregados = pd.read_parquet(f, engine='pyarrow')
print ('filas fichero agregation=',len(df_datos_agregados.index))

filas fichero agregation= 29294


Las primeras N filas del dataFrame se puede visualizar de la siguiente forma

In [19]:
N=4
df_datos_agregados.head(N)


Tag  FirstTimestamp  OriginalTimestamp           Time  Voltage   Current  \
0  start   1667813150658      1667813180464  1667813150658  243.036  0.138832   
1  start   1667813150658      1667813180464  1667813150858  242.976  0.128507   
2  start   1667813150658      1667813180464  1667813151058  243.006  0.127892   
3  start   1667813150658      1667813180464  1667813151258  242.986  0.129047   

   Frequency  Flag  Unbalance  Power_Factor      Phi  Active_Power  \
0    50.0063   0.0        0.0      0.522081  18.0151       17.6157   
1    50.0063   0.0        0.0      0.544893  20.3962       17.0138   
2    50.0063   0.0        0.0      0.533635  18.8721       16.5847   
3    50.0060   0.0        0.0      0.542866  21.4249       17.0224   

   Reactive_Power  Apparent_Power  Current_THD  Voltage_THD  \
0        -5.72538       18.522721      419.101      3.28028   
1        -6.33315       18.154254      416.543      3.28123   
2        -5.67179       17.527691      423.883      3.31052   
3        -6.68467       18.287857      408.878      3.30363   

                                     Power_Harmonics  \
0  [17.6052, -0.000427, 0.009401, 0.000193, -0.00...   
1  [17.0328, 0.000263, 0.007289, 9.2e-05, -0.0105...   
2  [16.5923, -0.000284, 0.00915, 9.6e-05, -0.0076...   
3  [17.0355, 4.4e-05, 0.009944, 8.9e-05, -0.01034...   

                           Voltage_Harmonics_Complex  \
0  [[24.7682, -241.729], [-0.022921, -0.065299], ...   
1  [[24.7901, -241.665], [0.024488, 0.04094], [1....   
2  [[24.5223, -241.724], [0.00477, -0.073629], [1...   
3  [[24.8806, -241.666], [0.002944, 0.012713], [1...   

                           Current_Harmonics_Complex  
0  [[0.030824, -0.069672], [0.004486, 0.00497], [...  
1  [[0.033088, -0.067087], [0.002579, 0.004884], ...  
2  [[0.030117, -0.065586], [0.001622, 0.003968], ...  
3  [[0.034552, -0.066935], [0.002081, 0.002974], ...

Y las N últimas filas

In [20]:
df_datos_agregados.tail(N)

Tag  FirstTimestamp  OriginalTimestamp  \
29290  [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]   1667818898226      1667819198641   
29291  [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]   1667818898226      1667819198641   
29292  [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]   1667818898226      1667819198641   
29293  [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]   1667818898226      1667819198641   

                Time  Voltage  Current  Frequency  Flag  Unbalance  \
29290  1667819008108  237.935  11.1608    49.9540   0.0        0.0   
29291  1667819008308  237.923  11.1654    49.9546   0.0        0.0   
29292  1667819008508  237.888  11.1596    49.9550   0.0        0.0   
29293  1667819008708  237.802  11.1533    49.9557   0.0        0.0   

       Power_Factor       Phi  Active_Power  Reactive_Power  Apparent_Power  \
29290      0.999898 -0.207064       2655.28         9.59250     2655.297112   
29291      0.999895 -0.241051       2656.21        11.17100     2656.236625   
29292      0.999890 -0.214605       2654.44         9.93879     2654.455130   
29293      0.999895 -0.236434       2652.01        10.93970     2652.029887   

       Current_THD  Voltage_THD  \
29290      5.48513      3.10864   
29291      5.31570      3.13847   
29292      5.34883      3.11950   
29293      5.40560      3.09375   

                                         Power_Harmonics  \
29290  [2654.29, -0.000507, 0.18802, 0.000372, 0.4223...   
29291  [2655.23, -0.000214, 0.185595, 1.6e-05, 0.4281...   
29292  [2653.48, 5.4e-05, 0.179573, 3e-06, 0.414696, ...   
29293  [2651.03, 0.00047, 0.175339, 1.6e-05, 0.422125...   

                               Voltage_Harmonics_Complex  \
29290  [[16.2439, -237.341], [-0.066995, -0.019419], ...   
29291  [[16.5515, -237.307], [-0.04716, -0.005576], [...   
29292  [[16.5604, -237.272], [-0.051595, 0.00372], [1...   
29293  [[16.7038, -237.176], [-0.049217, -0.014156], ...   

                               Current_Harmonics_Complex  
29290  [[0.721611, -11.134], [0.006547, 0.003527], [0...  
29291  [[0.729777, -11.1381], [0.005193, -0.005596], ...  
29292  [[0.735072, -11.132], [-0.001427, -0.005384], ...  
29293  [[0.737427, -11.1256], [-0.007245, -0.007988],...

Filtrar por un determinado valor

In [21]:
df_datos_agregados[df_datos_agregados.Unbalance ==0 ].head()

Tag  FirstTimestamp  OriginalTimestamp           Time  Voltage   Current  \
0  start   1667813150658      1667813180464  1667813150658  243.036  0.138832   
1  start   1667813150658      1667813180464  1667813150858  242.976  0.128507   
2  start   1667813150658      1667813180464  1667813151058  243.006  0.127892   
3  start   1667813150658      1667813180464  1667813151258  242.986  0.129047   
4  start   1667813150658      1667813180464  1667813151458  243.022  0.142382   

   Frequency  Flag  Unbalance  Power_Factor      Phi  Active_Power  \
0    50.0063   0.0        0.0      0.522081  18.0151       17.6157   
1    50.0063   0.0        0.0      0.544893  20.3962       17.0138   
2    50.0063   0.0        0.0      0.533635  18.8721       16.5847   
3    50.0060   0.0        0.0      0.542866  21.4249       17.0224   
4    50.0060   0.0        0.0      0.483124  20.9230       16.7171   

   Reactive_Power  Apparent_Power  Current_THD  Voltage_THD  \
0        -5.72538       18.522721      419.101      3.28028   
1        -6.33315       18.154254      416.543      3.28123   
2        -5.67179       17.527691      423.883      3.31052   
3        -6.68467       18.287857      408.878      3.30363   
4        -6.39622       17.898931      430.009      3.31426   

                                     Power_Harmonics  \
0  [17.6052, -0.000427, 0.009401, 0.000193, -0.00...   
1  [17.0328, 0.000263, 0.007289, 9.2e-05, -0.0105...   
2  [16.5923, -0.000284, 0.00915, 9.6e-05, -0.0076...   
3  [17.0355, 4.4e-05, 0.009944, 8.9e-05, -0.01034...   
4  [16.7299, 0.000169, 0.006445, 0.000143, -0.011...   

                           Voltage_Harmonics_Complex  \
0  [[24.7682, -241.729], [-0.022921, -0.065299], ...   
1  [[24.7901, -241.665], [0.024488, 0.04094], [1....   
2  [[24.5223, -241.724], [0.00477, -0.073629], [1...   
3  [[24.8806, -241.666], [0.002944, 0.012713], [1...   
4  [[25.2056, -241.669], [-0.001122, -0.043816], ...   

                           Current_Harmonics_Complex  
0  [[0.030824, -0.069672], [0.004486, 0.00497], [...  
1  [[0.033088, -0.067087], [0.002579, 0.004884], ...  
2  [[0.030117, -0.065586], [0.001622, 0.003968], ...  
3  [[0.034552, -0.066935], [0.002081, 0.002974], ...  
4  [[0.033324, -0.065751], [-0.003829, -0.003764]...

Filtramos por un valor numerico

In [22]:
df_datos_agregados[df_datos_agregados.Frequency >=50 ].head()

Tag  FirstTimestamp  OriginalTimestamp           Time  Voltage   Current  \
0  start   1667813150658      1667813180464  1667813150658  243.036  0.138832   
1  start   1667813150658      1667813180464  1667813150858  242.976  0.128507   
2  start   1667813150658      1667813180464  1667813151058  243.006  0.127892   
3  start   1667813150658      1667813180464  1667813151258  242.986  0.129047   
4  start   1667813150658      1667813180464  1667813151458  243.022  0.142382   

   Frequency  Flag  Unbalance  Power_Factor      Phi  Active_Power  \
0    50.0063   0.0        0.0      0.522081  18.0151       17.6157   
1    50.0063   0.0        0.0      0.544893  20.3962       17.0138   
2    50.0063   0.0        0.0      0.533635  18.8721       16.5847   
3    50.0060   0.0        0.0      0.542866  21.4249       17.0224   
4    50.0060   0.0        0.0      0.483124  20.9230       16.7171   

   Reactive_Power  Apparent_Power  Current_THD  Voltage_THD  \
0        -5.72538       18.522721      419.101      3.28028   
1        -6.33315       18.154254      416.543      3.28123   
2        -5.67179       17.527691      423.883      3.31052   
3        -6.68467       18.287857      408.878      3.30363   
4        -6.39622       17.898931      430.009      3.31426   

                                     Power_Harmonics  \
0  [17.6052, -0.000427, 0.009401, 0.000193, -0.00...   
1  [17.0328, 0.000263, 0.007289, 9.2e-05, -0.0105...   
2  [16.5923, -0.000284, 0.00915, 9.6e-05, -0.0076...   
3  [17.0355, 4.4e-05, 0.009944, 8.9e-05, -0.01034...   
4  [16.7299, 0.000169, 0.006445, 0.000143, -0.011...   

                           Voltage_Harmonics_Complex  \
0  [[24.7682, -241.729], [-0.022921, -0.065299], ...   
1  [[24.7901, -241.665], [0.024488, 0.04094], [1....   
2  [[24.5223, -241.724], [0.00477, -0.073629], [1...   
3  [[24.8806, -241.666], [0.002944, 0.012713], [1...   
4  [[25.2056, -241.669], [-0.001122, -0.043816], ...   

                           Current_Harmonics_Complex  
0  [[0.030824, -0.069672], [0.004486, 0.00497], [...  
1  [[0.033088, -0.067087], [0.002579, 0.004884], ...  
2  [[0.030117, -0.065586], [0.001622, 0.003968], ...  
3  [[0.034552, -0.066935], [0.002081, 0.002974], ...  
4  [[0.033324, -0.065751], [-0.003829, -0.003764]...

### GENERACION DE LOS FICHEROS PREPROCESADOS

En cada fichero  vamos a calcular la potencia aparente para cada valor de timestamp

Por otro lado tambien necesitamos obtener la parte entera del valor de los armonicos de tension y cortriente  mediante la funcion modulo , por lo que tenemos qeu aplicar esa funcion a los datos del fichero

Asismimo es encesario reorganizar las columnas en el orden acordado en nilmtk


En los ficheros de datos no nos es util el valor autoincremental  al no ser una variable electrica . Recordar que este valor es  usado como indice del dataset. 

Para ello ,usaremos como indice el valor del timestamp, dado que este valor es biunivoco.

Vamos a reconstruir los ficheros csv eliminando pues ese campo.

In [23]:
 
    
    
    
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_fan_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('fan.csv') 



## Generación del fichero de datos a partir del fichero ozm_fan_200MS.parquet

In [24]:
 
    
    
    
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_fan_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('fan.csv') 



## Generación del fichero de datos a partir del fichero ozm_freezer_200MS.parquet  

In [25]:
 
    
    
    
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_freezer_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('freezer.csv') 



## Generación del fichero de datos a partir del fichero ozm_monitor_200MS.parquet

In [26]:
    
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_monitor_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('monitor.csv') 


## Generación del fichero de datos a partir del fichero ozm_vacuum_cleaner_200MS.parquet 

In [27]:
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_vacuum_cleaner_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)


df_reset.to_csv('vacuum_cleaner.csv')

#print (df_reset)
    
#df    

## Generación del fichero de datos a partir del fichero water_heater.h5  

In [28]:
    
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_water_heater_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)


df_reset.to_csv('water_heater.csv')

#print (df_reset)
    
#df    

## Generación del fichero de datos a partir del fichero ozm_kettle_200MS.parquet 

In [29]:
  
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_kettle_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('kettle.csv') 

## Generación del fichero de datos a partir del fichero ozm_fridge_200MS.parquet 

In [30]:
  
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_fridge_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('fridge.csv') 

## Generación del fichero de datos a partir del fichero ozm_microvawe_200MS.parquet

In [31]:
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_microvawe_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('microwave.csv') 

## Generación del fichero de datos a partir del fichero ozm_oil_heater_200MS.parquet

In [32]:
  
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_oil_heater_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('oil_heater.csv') 

## Generación del fichero de datos a partir del fichero ozm_oven_200MS.parquet

In [33]:
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_oven_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('oven.csv') 

## Generación del fichero de datos a partir del fichero ozm_aggregation_200MS.parquet

In [34]:
  
import pandas as pd
import glob
import math
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import export_png
# select a palette
from bokeh.palettes import Category10




df_path = ".\data\ozm1\ozm_aggregation_200MS.parquet"
#print(os.path.exists(df_path))
#print(os.getcwd())
df = pd.read_parquet(df_path)  #leemos todo el fichero y lo cargamos en un dataframe





# se calcula todo en una sola vez para todo el dataframe
#item = df['Voltage_Harmonics_Complex']  #recupera de la fila 1 el voltaje complejo
#print(item)
#print(type(item))
df = df.applymap(array_to_list)  #crea un dataframe de listas
#item = df['Voltage_Harmonics_Complex']
#print(item)
#print(type(item))
df = df.applymap(modulus) #crea un dataframe con los modulos

#almacenamos el voltaje complejo
item = df['Voltage_Harmonics_Complex']
#print(item)

#almacenamos la corriente compleja
items = df['Current_Harmonics_Complex']
#print(items)


#eliminamos columnas que no vamos a necesitar
df.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Tag'],axis = 'columns', inplace=True)


#insertamos nuevas columnas en el dataframe
df.insert (1,'Voltage_Harmonics_Complex',item)
df.insert (2,'Current_Harmonics_Complex',items)



#renombramos columnas
df.rename(columns={'Time':'timestamp','Active_Power':'W','Reactive_Power':'VAR','Apparent_Power':'VA' },inplace=True)
df.rename(columns={'Frequency':'f','Voltage':'VLN','Power_Factor':'PF','Current':'A' },inplace=True)

#eliminamos columnas que no vamos a necesitar
#df.drop (['FirstTimestamp','OriginalTimestamp','Tag'],axis = 'columns', inplace=True)

#eliminamos columnas que no vamos a necesitar
df.drop (['FirstTimestamp','OriginalTimestamp'],axis = 'columns', inplace=True)


#df_datos_agregados.drop (['Voltage_Harmonics_Complex','Current_Harmonics_Complex','Power_Harmonics'],axis = 'columns', inplace=True)
df.drop (['Flag','Unbalance','Phi'],axis = 'columns', inplace=True)

#reordenamos las columnas
df=df [['timestamp','W','VAR','VA','f','VLN','PF','A','Voltage_Harmonics_Complex',  'Current_Harmonics_Complex','Power_Harmonics' ]]

#eliminamos columna indice y la sustituimos por el campo timestamp
df_reset=df.set_index('timestamp')

#print (df_reset)

df_reset.to_csv('aggregation.csv') 

## Analisis fechas


In [35]:
import pandas as pd

with open(r'.\data\ozm1\ozm_aggregation_200MS.parquet', 'rb') as f:
    df_datos_agregados = pd.read_parquet(f, engine='pyarrow')

print ('filas fichero aggregation.hdf5=',len(df_datos_agregados.index))

filas fichero aggregation.hdf5= 29294


In [36]:
N=1
df_datos_agregados.head(N)

Tag  FirstTimestamp  OriginalTimestamp           Time  Voltage   Current  \
0  start   1667813150658      1667813180464  1667813150658  243.036  0.138832   

   Frequency  Flag  Unbalance  Power_Factor      Phi  Active_Power  \
0    50.0063   0.0        0.0      0.522081  18.0151       17.6157   

   Reactive_Power  Apparent_Power  Current_THD  Voltage_THD  \
0        -5.72538       18.522721      419.101      3.28028   

                                     Power_Harmonics  \
0  [17.6052, -0.000427, 0.009401, 0.000193, -0.00...   

                           Voltage_Harmonics_Complex  \
0  [[24.7682, -241.729], [-0.022921, -0.065299], ...   

                           Current_Harmonics_Complex  
0  [[0.030824, -0.069672], [0.004486, 0.00497], [...

In [37]:
FirstTimestamp=df_datos_agregados.iat[0,1]

In [38]:
OriginalTimestamp=df_datos_agregados.iat[0,2]

In [39]:
Time=df_datos_agregados.iat[0,3]

In [40]:
import pandas as pd
import numpy as np
import datetime
df=pd.DataFrame()

i=[FirstTimestamp,OriginalTimestamp,Time]
df['date']=pd.Series(i)
df['date']=df['date'].apply(lambda d: datetime.datetime.fromtimestamp(int(d)/1000).strftime('%Y-%m-%d %H:%M:%S'))

df



date
0  2022-11-07 10:25:50
1  2022-11-07 10:26:20
2  2022-11-07 10:25:50

In [41]:
df_datos_agregados.tail(N)

Tag  FirstTimestamp  OriginalTimestamp  \
29293  [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]   1667818898226      1667819198641   

                Time  Voltage  Current  Frequency  Flag  Unbalance  \
29293  1667819008708  237.802  11.1533    49.9557   0.0        0.0   

       Power_Factor       Phi  Active_Power  Reactive_Power  Apparent_Power  \
29293      0.999895 -0.236434       2652.01         10.9397     2652.029887   

       Current_THD  Voltage_THD  \
29293       5.4056      3.09375   

                                         Power_Harmonics  \
29293  [2651.03, 0.00047, 0.175339, 1.6e-05, 0.422125...   

                               Voltage_Harmonics_Complex  \
29293  [[16.7038, -237.176], [-0.049217, -0.014156], ...   

                               Current_Harmonics_Complex  
29293  [[0.737427, -11.1256], [-0.007245, -0.007988],...

In [42]:
FirstTimestamp1=df_datos_agregados.iat[29293,1]

In [43]:
OriginalTimestamp1=df_datos_agregados.iat[29293,2]

In [44]:
Time1 =df_datos_agregados.iat[29293,3]

In [45]:
import pandas as pd
import numpy as np
import datetime
df=pd.DataFrame()

i=[FirstTimestamp1,OriginalTimestamp1,Time1]
df['date']=pd.Series(i)
df['date']=df['date'].apply(lambda d: datetime.datetime.fromtimestamp(int(d)/1000).strftime('%Y-%m-%d %H:%M:%S'))

df


date
0  2022-11-07 12:01:38
1  2022-11-07 12:06:38
2  2022-11-07 12:03:28

## Eliminacion de caracteres en fichero csv y localizacion en ruta de conversion

### 1- Procesado fichero aggregation.csv

In [46]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('aggregation.csv','r') as firstfile, open('./data/ozm1/electricity/1.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 2- Procesado fichero water_heater.csv

In [47]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('water_heater.csv','r') as firstfile, open('./data/ozm1/electricity/8.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 3- Procesado fichero fan.csv

In [48]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('fan.csv','r') as firstfile, open('./data/ozm1/electricity/9.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 4- Procesado fichero freezer

In [49]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('freezer.csv','r') as firstfile, open('./data/ozm1/electricity/11.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 5-Procesado fichero monitor.csv

In [50]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('monitor.csv','r') as firstfile, open('./data/ozm1/electricity/4.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 6-Procesado fichero vacuum_cleaner.csv

In [51]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('vacuum_cleaner.csv','r') as firstfile, open('./data/ozm1/electricity/6.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 7-Procesado fichero kettle.csv

In [52]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('kettle.csv','r') as firstfile, open('./data/ozm1/electricity/5.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 8-Procesado fichero fridge.csv

In [53]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('fridge.csv','r') as firstfile, open('./data/ozm1/electricity/10.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 9-Procesado fichero microwave.csv


In [54]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('microwave.csv','r') as firstfile, open('./data/ozm1/electricity/3.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 10-Procesado fichero oil_heater.csv

In [55]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('oil_heater.csv','r') as firstfile, open('./data/ozm1/electricity/7.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 

### 11-Procesado fichero oven.csv

In [56]:
import re
#copia el contenido de un fichero en otro
OLD= 'timestamp,W,VAR,VA,f,VLN,PF,A,Voltage_Harmonics_Complex,Current_Harmonics_Complex,Power_Harmonics'
NUEVO='timestamp,W,VAR,VA,f,VLN,PF,A,VH1,VH2,VH3,VH4,VH5,VH6,VH7,VH8,VH9,VH10,VH11,VH12,VH13,VH14,VH15,VH16,VH17,VH18,VH19,VH20,VH21,VH22,VH23,VH24,VH25,VH26,VH27,VH28,VH29,VH30,VH31,VH32,VH33,VH34,VH35,VH36,VH37,VH38,VH39,VH40,VH41,VH42,VH43,VH44,VH45,VH46,VH47,VH48,VH49,VH50,IH1,IH2,IH3,IH4,IH5,IH6,IH7,IH8,IH9,IH10,IH11,IH12,IH13,IH14,IH15,IH16,IH17,IH18,IH19,IH20,IH21,IH22,IH23,IH24,IH25,IH26,IH27,IH28,IH29,IH30,IH31,IH32,IH33,IH34,IH35,IH36,IH37,IH38,IH39,IH40,IH41,IH42,IH43,IH44,IH45,IH46,IH47,IH48,IH49,IH50,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,PH16,PH17,PH18,PH19,PH20,PH21,PH22,PH23,PH24,PH25,PH26,PH27,PH28,PH29,PH30,PH31,PH32,PH33,PH34,PH35,PH36,PH37,PH38,PH39,PH40,PH41,PH42,PH43,PH44,PH45,PH46,PH47,PH48,PH49,PH50'
with open('oven.csv','r') as firstfile, open('./data/ozm1/electricity/2.csv','a') as secondfile: 
    
    for line in firstfile: 
        line2=line.replace(OLD,NUEVO)
        line2 = line2.replace('"[', '')
        line2 = line2.replace(']"', '')    
     
      #  print (line2)
        secondfile.write(line2) 